- name: Setup Jumpbox
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Get the latest stable Kubernetes version string
      uri:
        url: https://dl.k8s.io/release/stable.txt
        return_content: yes
      register: k8s_version
    
    - name: Download the corresponding kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/{{ k8s_version.content | trim }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
        owner: root
        group: root

    - name: Split S3 URI
      set_fact:
        s3_bucket: "{{ (s3_pem_path | regex_replace('^s3://', '') | split('/'))[0] }}"
        s3_object: "{{ (s3_pem_path | regex_replace('^s3://', '') | split('/'))[1:] | join('/') }}"

    - name: Download node access PEM
      aws_s3:
        bucket: "{{ s3_bucket }}"
        object: "{{ s3_object }}"
        dest: "/home/ec2-user/{{ s3_object | basename }}"
        mode: get

    - name: Restrict PEM access
      file:
        path: "/home/ec2-user/{{ s3_object | basename }}"
        mode: '600'
